/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTEXPR = 0;
  public int JJTVOID = 1;
  public int JJTPLUS = 2;
  public int JJTID = 3;


  public String[] jjtNodeName = {
    "Expr",
    "void",
    "Plus",
    "Id",
  };
}
/* JavaCC - OriginalChecksum=ebe7e437319c906f408efa71505b5fdf (do not edit this line) */
