/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTExpr node, Object data);
  public Object visit(ASTPlus node, Object data);
  public Object visit(ASTId node, Object data);
}
/* JavaCC - OriginalChecksum=742a8d5c40f504f09b58ec40e6606cf2 (do not edit this line) */
